name: fb
version: '2.0.0'
synopsis: Bindings to Facebook's API.
description: ! 'This package exports bindings to Facebook''s APIs (see

  <http://developers.facebook.com/>).  Does not have any external

  dependencies and tries to use as little resources (such as

  memory, sockets and CPU) as possible by using packages such as

  @aeson@, @attoparsec@, @bytestring@, @conduit@, @http-conduit@,

  @text@ and others.


  While we would like to have a complete binding to Facebook''s

  API, this package is being developed on demand.  If you need

  something that has not been implemented yet, please send a pull

  request or file an issue on GitHub

  (<https://github.com/psibi/fb/issues>).'
category: Web
author: Felipe Lessa, Sibi Prabakaran
maintainer: Sibi <sibi@psibi.in>
copyright: Felipe Lessa and Sibi Prabakaran
license: BSD3
homepage: https://github.com/psibi/fb
git: git@github.com:psibi/fb.git
bug-reports: https://github.com/psibi/fb/issues
extra-source-files:
- tests/Main.hs
- tests/tryIt.hs
- example.hs
- README.md
- CHANGELOG.md
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Facebook
  dependencies:
  - base >=4 && <5
  - bytestring >=0.9 && <0.11
  - text >=0.11 && <1.3
  - transformers >=0.2 && <0.6
  - transformers-base
  - http-types
  - http-conduit >=2.3.0
  - http-client >=0.4.30
  - attoparsec >=0.10.4 && <0.14
  - unordered-containers
  - data-default
  - aeson >=0.8.0.2
  - base16-bytestring >=0.1
  - base64-bytestring >=0.1.1
  - time >=1.4
  - old-locale
  - cereal >=0.3 && <0.6
  - cryptonite
  - memory
  - monad-logger >=0.3.28
  - conduit-extra >= 1.3.0
  - unliftio
  - unliftio-core
  - resourcet >= 1.2.0
  - conduit >= 1.3.0
  when:
  - condition: flag(debug)
    cpp-options: -DDEBUG
tests:
  runtests:
    main: Main.hs
    source-dirs: tests
    ghc-options:
    - -Wall
    - -fno-warn-orphans
    dependencies:
    - base
    - transformers
    - bytestring
    - http-conduit
    - text
    - time
    - aeson
    - containers
    - HUnit
    - QuickCheck
    - hspec >= 2.5.0
    - conduit
    - resourcet
    - data-default
    - unliftio
    - fb
flags:
  debug:
    description: Print debugging info.
    manual: false
    default: false
stability: Experimental
